Repository React-Bootcamp-WoMarkersCode/call-of-papers, pull requests merged in 2020-03, with the labels that each got.

#24 Tela de "Lista de Eventos"
  call-of-papers/src/mock.js
  call-of-papers/src/pages/Events/EventsList.js
Labels: enhancement

#25 Criação de um novo Readme
  README.md
Labels: documentation

#30 Correção do link da imagem do wireframe no Readme
  README.md
Labels: invalid

#34 Inclusão da folha de estilo na tela de "Lista de eventos"
  call-of-papers/src/pages/Events/EventsList.js
  call-of-papers/src/pages/Events/events-list-test.js
  call-of-papers/src/pages/Events/events-list.scss
Labels: invalid

#33 Tela de "Página do Evento"
  call-of-papers/src/pages/Events/Event.js
  call-of-papers/src/pages/Events/event.scss
Labels: enhancement

#37 URGENT: Event list mock
  call-of-papers/src/pages/Events/Event.js
  call-of-papers/src/pages/Events/event.scss
  call-of-papers/src/pages/Home/Home.js
Labels: bug

#39 My profile page
  call-of-papers/package-lock.json
  call-of-papers/src/App.js
  call-of-papers/src/pages/MyProfile.js
Labels: enhancement
