Repository React-Bootcamp-WoMarkersCode/call-of-papers, pull requests merged in 2020-04, with the labels that each got.

#45 Partners bug fixed
  call-of-papers/src/App.js
Labels: bug

#55 Implementação do Back-end - (Json-server)
  call-of-papers/package-lock.json
  call-of-papers/package.json
  call-of-papers/server.json
Labels: revisar

#46 Cria login com facebook
  call-of-papers/package-lock.json
  call-of-papers/package.json
  call-of-papers/src/components/Menu/index.js
  call-of-papers/src/pages/Home/Home.js
  call-of-papers/src/pages/Login/FBLogin.js
  call-of-papers/src/pages/Login/GglLogin.js
  call-of-papers/src/pages/MyProfile.js
Labels: revisar

#57 Atualizando o readme com a documentação do Json-serve
  call-of-papers/README.md
Labels: documentação

#59 Correção das páginas Meus eventos e Eventos
  call-of-papers/package-lock.json
  call-of-papers/package.json
  call-of-papers/server.json
  call-of-papers/src/pages/Events/Event.js
  call-of-papers/src/pages/Events/EventForm.js
  call-of-papers/src/pages/Events/EventsList.js
Labels: revisar

#66 Urgência: Correção na npm start
  call-of-papers/package-lock.json
  call-of-papers/package.json
Labels: bug

#60 WIP: Tela do Formulário Evento
  call-of-papers/server.json
  call-of-papers/src/pages/Events/EventForm.js
Labels: bug

#61 WIP - Problemas com Formik (2)
  call-of-papers/src/pages/Lectures/LectureForm.js
Labels: bug

#65 Edição de Perfil
  call-of-papers/package-lock.json
  call-of-papers/package.json
  call-of-papers/server.json
  call-of-papers/src/Routes.js
  call-of-papers/src/components/Menu/index.js
  call-of-papers/src/pages/Login/FBLogin.js
  call-of-papers/src/pages/MyProfile.js
  call-of-papers/src/pages/Profile/MyProfile.css
  call-of-papers/src/pages/Profile/MyProfile.js
  call-of-papers/src/pages/Profile/ProfileForm.js
  call-of-papers/src/utils/currentDate.js
  call-of-papers/src/utils/environment.js
Labels: desenvolvimento

#78 Refactor/padronize ant design
  call-of-papers/config-overrides.js
  call-of-papers/package-lock.json
  call-of-papers/package.json
  call-of-papers/server.json
  call-of-papers/src/App.js
  call-of-papers/src/ant_overrides.scss
  call-of-papers/src/assets/logo.jpeg
  call-of-papers/src/components/Footer/index.js
  call-of-papers/src/components/Menu/index.js
  call-of-papers/src/components/Menu/style.scss
  call-of-papers/src/components/Table/index.js
  call-of-papers/src/components/Table/style.scss
  call-of-papers/src/index.js
  call-of-papers/src/index.scss
  call-of-papers/src/pages/About/index.js
  call-of-papers/src/pages/Events/EventForm.js
  call-of-papers/src/pages/Events/EventsList.js
  call-of-papers/src/pages/Events/events-list-test.js
  call-of-papers/src/pages/Events/events-list.scss
  call-of-papers/src/pages/Home/CardEvent.js
  call-of-papers/src/pages/Home/Home.js
  call-of-papers/src/pages/Home/style.scss
  call-of-papers/src/pages/Lectures/LectureForm.js
  call-of-papers/src/pages/Lectures/LecturesList.js
  call-of-papers/src/pages/Lectures/lectures-list-test.json
  call-of-papers/src/pages/Lectures/lectures-list.scss
  call-of-papers/src/pages/Login/FBLogin.js
  call-of-papers/src/pages/Login/GglLogin.js
  call-of-papers/src/theme.js
  call-of-papers/yarn.lock
Labels: desenvolvimento

#87 Fix: reset active tab on home page
  call-of-papers/src/components/Menu/index.js
Labels: bug

#81 Refactor/profile and about screens
  call-of-papers/src/ant_overrides.scss
  call-of-papers/src/index.scss
  call-of-papers/src/pages/About/index.js
  call-of-papers/src/pages/Profile/MyProfile.css
  call-of-papers/src/pages/Profile/MyProfile.js
  call-of-papers/src/pages/Profile/ProfileDescription.js
  call-of-papers/src/pages/Profile/ProfileForm.js
  call-of-papers/src/pages/Profile/style.scss
Labels: desenvolvimento

#72 Download de palestras em csv
  call-of-papers/src/Routes.js
  call-of-papers/src/pages/Lectures/LecturesCSV.js
  call-of-papers/src/pages/Lectures/LecturesList.js
  call-of-papers/src/utils/convertToCSV.js
Labels: desenvolvimento

#82 Feat: Header for not logged users
  call-of-papers/src/App.js
  call-of-papers/src/components/Menu/index.js
  call-of-papers/src/components/Menu/style.scss
  call-of-papers/src/pages/Login/FBLogin.js
  call-of-papers/src/pages/Login/fb_style.scss
Labels: desenvolvimento

#86 WIP - Error fazer a troca do form editar para form de editar
  call-of-papers/server.json
  call-of-papers/src/Routes.js
  call-of-papers/src/pages/Events/Event.js
  call-of-papers/src/pages/Events/EventForm.js
  call-of-papers/src/pages/Events/EventsList.js
Labels: bug

#92 Refactor/lectures layout
  call-of-papers/server.json
  call-of-papers/src/ant_overrides.scss
  call-of-papers/src/index.scss
  call-of-papers/src/pages/About/index.js
  call-of-papers/src/pages/Lectures/Lecture.js
  call-of-papers/src/pages/Lectures/LectureForm.js
  call-of-papers/src/pages/Lectures/LecturesCSV.js
  call-of-papers/src/pages/Lectures/LecturesList.js
  call-of-papers/src/pages/Lectures/lectures-list-test.json
  call-of-papers/src/pages/Lectures/lectures-list.scss
  call-of-papers/src/pages/Login/fb_style.scss
  call-of-papers/src/pages/Profile/style.scss
Labels: desenvolvimento

#94 Ajustes no layout das telas de submissão
  call-of-papers/server.json
  call-of-papers/src/pages/Lectures/LecturesList.js
  call-of-papers/src/pages/Submissions/style.scss
  call-of-papers/src/pages/Submissions/submission.js
  call-of-papers/src/pages/Submissions/submissionsList.js
Labels: desenvolvimento

#101 Corrigindo rota da Home para os detalhes dos eventos
  call-of-papers/src/pages/Home/CardEvent.js
  call-of-papers/src/pages/Home/Home.js
Labels: bug

#99 Remover imagens dos cards da home
  call-of-papers/src/pages/Home/CardEvent.js
Labels: bug

#96 Ajustes no layout das telas de eventos
  call-of-papers/src/pages/Events/Event.js
  call-of-papers/src/pages/Events/EventForm.js
  call-of-papers/src/pages/Events/EventsList.js
Labels: desenvolvimento

#103 Correção do merge da nova tela de Home
  call-of-papers/src/pages/Home/CardEvent.js
Labels: bug

#102 JEST - Teste de cadastro de evento
  call-of-papers/README.md
  call-of-papers/package-lock.json
  call-of-papers/package.json
  call-of-papers/src/App.test.js
  call-of-papers/src/pages/Events/event-register.js
  call-of-papers/src/pages/Events/event-register.test.js
Labels: desenvolvimento

#80 WIP - Ajuste do formulario de palestras (página travando)
  call-of-papers/src/pages/Lectures/LectureForm.js
Labels: bug

#104 Correção no radio para não limpar o form
  call-of-papers/src/pages/Events/EventForm.js
Labels: bug

#114 Update readme
  README.md
Labels: documentação

#115 Importar fonte Roboto do Google
  src/index.scss
Labels: desenvolvimento

#116 Enviar eventId no formulário de Palestras
  src/pages/Lectures/LectureForm.js
Labels: bug

#123 Refactor/final layout logo
  README.md
  public/favicon.ico
  public/index.html
  public/logo.png
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.js
  src/ant_overrides.scss
  src/assets/logo.jpeg
  src/assets/logo.png
  src/components/Menu/index.js
  src/components/Menu/style.scss
  src/components/Table/style.scss
  src/index.scss
  src/pages/About/index.js
  src/pages/Events/event-register.test.js
  src/pages/Home/style.scss
  src/pages/Login/fb_style.scss
  src/pages/Profile/style.scss
  src/pages/Submissions/submission.js
  src/utils/Email/Back.js
Labels: desenvolvimento

#145 Novo Header + Correção de login forçado com Facebook
  src/Routes.js
  src/components/Menu/index.js
  src/components/Menu/style.scss
  src/pages/Login/FBLogin.js
  src/pages/Login/index.js
Labels: bug, desenvolvimento

#151 Nova tela de login
  package.json
  src/assets/both.png
  src/components/Menu/index.js
  src/components/Menu/style.scss
  src/pages/Login/index.js
  src/pages/Login/style.scss
Labels: desenvolvimento

#164 Limitar visualização da plataforma para perfis de usuários
  server.json
  src/ant_overrides.scss
  src/components/Menu/index.js
  src/components/Menu/style.scss
  src/pages/Login/FBLogin.js
  src/pages/Login/index.js
  src/pages/Login/style.scss
  src/pages/Profile/ProfileDescription.js
  src/pages/Profile/ProfileForm.js
Labels: desenvolvimento

#166 Remover menu da tela de login
  src/components/Menu/index.js
Labels: desenvolvimento

#168 Remover yarn.lock
  yarn.lock
Labels: bug

#180 Novo layout para página de eventos e palestras sem cadastros
  src/Routes.js
  src/components/Menu/style.scss
  src/index.scss
  src/pages/Events/EventsList.js
  src/pages/Lectures/LecturesList.js
Labels: desenvolvimento

#189 Notificações de confirmação nos formulários
  src/pages/Events/EventForm.js
  src/pages/Events/PartnersForm.js
  src/pages/Lectures/CopyLecture.js
  src/pages/Lectures/LectureForm.js
Labels: desenvolvimento

#190 Correção do botão de criar nova palestra na página do palestrante
  src/index.scss
  src/pages/Lectures/LectureForm.js
  src/pages/Lectures/LecturesList.js
  src/pages/Lectures/lectures-list.scss
Labels: bug, desenvolvimento

#216 Alinhar card de eventos
  src/pages/Home/CardEvent.js
Labels: desenvolvimento

#267 Atualização da readme
  README.md
Labels: documentação

#268 Novo layout do email
  src/assets/banner.png
  src/pages/Lectures/LectureForm.js
  src/pages/Submissions/SubmissionsPending.js
Labels: desenvolvimento
